import type { StoryListItem } from './types';

export const MOCK_STORIES: StoryListItem[] = [
  {
    id: 1,
    title: '달빛 아래의 계약',
    summary: '기억을 잃은 마법사가 금지된 숲에서 자신의 과거를 추적하는 이야기',
    genres: ['FANTASY', 'MYSTERY'],
    authorNickname: 'manyak_writer',
    chatCount: 128,
    likeCount: 32,
    status: 'PUBLISHED',
    createdAt: '2026-06-10T12:00:00Z',
  },
  {
    id: 2,
    title: '회귀한 악녀는 도망치고 싶다',
    summary:
      '처형 직전 과거로 돌아온 악녀가 운명을 피하기 위해 황궁을 떠나려는 이야기',
    genres: ['ROMANCE_FANTASY', 'REGRESSION'],
    authorNickname: 'moon_archive',
    chatCount: 94,
    likeCount: 41,
    status: 'PUBLISHED',
    createdAt: '2026-06-11T09:30:00Z',
  },
  {
    id: 3,
    title: '던전 관리자의 비밀 장부',
    summary:
      '평범한 회계원이 던전 운영 시스템에 접속하며 몬스터들의 생존 전략을 설계하는 이야기',
    genres: ['GAME_FANTASY', 'DUNGEON'],
    authorNickname: 'system_master',
    chatCount: 211,
    likeCount: 76,
    status: 'PUBLISHED',
    createdAt: '2026-06-12T15:10:00Z',
  },
  {
    id: 4,
    title: '좀비 도시의 마지막 라디오',
    summary:
      '폐허가 된 도시에서 유일하게 송출되는 라디오 방송을 따라 생존자들이 모여드는 이야기',
    genres: ['POST_APOCALYPSE', 'ZOMBIE'],
    authorNickname: 'radio_zero',
    chatCount: 67,
    likeCount: 19,
    status: 'PUBLISHED',
    createdAt: '2026-06-13T18:45:00Z',
  },
  {
    id: 5,
    title: '황녀의 가짜 약혼자',
    summary:
      '몰락 귀족 출신 기사가 황녀의 가짜 약혼자가 되어 궁중 암투에 휘말리는 이야기',
    genres: ['ROMANCE_FANTASY', 'PALACE_INTRIGUE'],
    authorNickname: 'velvet_pen',
    chatCount: 156,
    likeCount: 58,
    status: 'PUBLISHED',
    createdAt: '2026-06-14T11:20:00Z',
  },
  {
    id: 6,
    title: '탑의 99층에서 만난 신',
    summary:
      '탑의 마지막 층에 도달한 헌터가 자신을 이곳으로 부른 신의 정체를 마주하는 이야기',
    genres: ['HUNTER', 'TOWER_CLIMBING'],
    authorNickname: 'floor_99',
    chatCount: 302,
    likeCount: 104,
    status: 'PUBLISHED',
    createdAt: '2026-06-15T07:55:00Z',
  },
  {
    id: 7,
    title: '첫사랑은 계약서에 없다',
    summary:
      '비밀스러운 사내 계약연애를 시작한 두 사람이 진짜 감정을 숨기지 못하게 되는 이야기',
    genres: ['OFFICE_ROMANCE', 'CONTRACT_LOVE'],
    authorNickname: 'daily_romance',
    chatCount: 83,
    likeCount: 27,
    status: 'PUBLISHED',
    createdAt: '2026-06-15T21:05:00Z',
  },
  {
    id: 8,
    title: '무림맹 막내 제자의 복수',
    summary:
      '스승의 죽음 뒤 배신자를 추적하던 막내 제자가 무림맹의 거대한 음모를 파헤치는 이야기',
    genres: ['MARTIAL_ARTS', 'REVENGE'],
    authorNickname: 'sword_cloud',
    chatCount: 174,
    likeCount: 63,
    status: 'PUBLISHED',
    createdAt: '2026-06-16T13:40:00Z',
  },
  {
    id: 9,
    title: '빙의했더니 최종 보스의 비서',
    summary:
      '소설 속 최종 보스의 비서로 빙의한 주인공이 멸망 엔딩을 막기 위해 상사를 설득하는 이야기',
    genres: ['POSSESSION', 'FANTASY'],
    authorNickname: 'plot_twister',
    chatCount: 245,
    likeCount: 89,
    status: 'PUBLISHED',
    createdAt: '2026-06-17T10:15:00Z',
  },
  {
    id: 10,
    title: '비 오는 날의 탐정 사무소',
    summary:
      '매번 비가 오는 날에만 사건 의뢰를 받는 탐정이 사라진 기억과 연쇄 실종 사건을 쫓는 이야기',
    genres: ['MYSTERY', 'THRILLER'],
    authorNickname: 'rainy_detective',
    chatCount: 119,
    likeCount: 36,
    status: 'PUBLISHED',
    createdAt: '2026-06-18T08:25:00Z',
  },
];
