export const TOAST_MESSAGE = {
  STORY_DRAFT_SAVED: '임시 저장했어요',
  STORY_DRAFT_SAVE_FAILED: '작성 내용을 저장하지 못했어요',
  STORY_DRAFT_LOAD_FAILED: '작성 내용을 불러오지 못했어요',
  STORY_COMPLETED: '스토리가 완성되었어요',
  STORY_COMPLETE_FAILED: '스토리를 완성하지 못했어요',
  STORY_REVIEWING: '스토리를 검토하고 있어요',
  STORY_REVIEW_REJECTED: '스토리가 검토를 통과하지 못했어요',
  STORY_REVIEW_DELAYED: '검토가 늦어지고 있어요. 끝나면 제작 탭에 추가돼요',
  STORY_REGISTER_FAILED: '스토리를 등록하지 못했어요',
  STORY_IMAGES_TOO_LARGE: '이미지 크기나 장수를 줄여 주세요',
  STORY_IMAGE_NOT_FOUND:
    '올린 이미지를 찾지 못했어요. 이미지를 다시 올려 주세요',
  STORY_SUBMISSION_PENDING: '아직 검토 중이에요',
  STORY_SUBMISSION_LOAD_FAILED: '스토리를 불러오지 못했어요',
  STORY_REGISTER_CANCELED: '등록을 취소했어요',
  STORY_REGISTER_CANCEL_FAILED: '등록을 취소하지 못했어요',
  STORY_EDITED: '스토리를 수정했어요',
  STORY_EDIT_FAILED: '스토리를 수정하지 못했어요',
  STORY_EDIT_REVIEW_DELAYED: '검토가 늦어지고 있어요. 끝나면 스토리에 반영돼요',
  STORY_DELETED: '스토리가 삭제되었어요',
  CHAT_DELETED: '채팅이 삭제되었어요',
  STORY_DELETE_FAILED: '스토리 삭제에 실패했어요',
  CHAT_DELETE_FAILED: '채팅 삭제에 실패했어요',
  STORY_LIKE_FAILED: '좋아요 변경에 실패했어요',
  STORY_REPORTED: '신고가 접수되었어요',
  STORY_REPORT_FAILED: '신고를 접수하지 못했어요',
  CHAT_START_FAILED: '채팅을 시작하지 못했어요',
  PERSONA_CREATED: '페르소나를 생성했어요',
  PERSONA_CREATE_FAILED: '페르소나를 생성하지 못했어요',
  PERSONA_LIMIT_REACHED: '페르소나는 10개까지 만들 수 있어요',
  CHAT_SHARE_LINK_COPIED: '채팅 공개 링크가 복사되었어요',
  CHAT_SHARE_FAILED: '공유 링크 생성에 실패했어요',
  STORYLINE_LIKED: '좋아요를 남겼어요',
  STORYLINE_DISLIKED: '싫어요를 남겼어요',
  STORYLINE_EVALUATE_FAILED: '평가 저장에 실패했어요',
  RESPONSE_STREAM_FAILED: '응답 생성에 실패했어요',
  CREDIT_SHORTAGE: '이프가 부족해요',
  CHAT_COMPOSER_LOCKED: '응답을 만드는 중이에요. 끝나면 입력할 수 있어요',
  GUEST_TRIAL_LIMIT: '게스트 체험 한도를 모두 사용했어요',
  FEEDBACK_SUBMITTED: '소중한 피드백을 보내주셔서 감사해요',
  FEEDBACK_SUBMIT_FAILED: '피드백 전송에 실패했어요',
  ACCOUNT_DELETION_FAILED: '회원 탈퇴에 실패했어요',
  LOGIN_FAILED: '로그인에 실패했어요',
  SIGNUP_CONSENT_EXPIRED: '로그인 시간이 지났어요. 다시 로그인해주세요',
  SIGNUP_CONSENT_OUTDATED: '약관이 갱신되었어요. 다시 로그인해주세요',
  SESSION_EXPIRED: '세션이 만료되어 로그아웃되었어요',
  MIGRATION_SUCCEEDED: (storyCount: number, chatCount: number) =>
    `스토리 ${storyCount}개, 채팅 ${chatCount}개를 계정으로 옮겼어요`,
  MIGRATION_ALREADY_DONE:
    '이미 스토리와 채팅을 옮긴 이력이 있어 옮기지 못했어요',
  ATTENDANCE_CLAIMED: (amount: number) =>
    `출석 체크 보상으로 ${amount} 이프를 받았어요`,
  ATTENDANCE_ALREADY: '오늘은 이미 출석 체크했어요',
  ATTENDANCE_FAILED: '출석 체크에 실패했어요',
  CREDIT_ORDER_FAILED: '결제를 시작하지 못했어요',
  INVITE_CODE_COPIED: '초대 코드를 복사했어요',
  INVITE_CODE_COPY_FAILED: '초대 코드 복사에 실패했어요',
  INVITE_ONBOARDING_SAVE_FAILED: '창을 닫지 못했어요',
  INVITE_SHARE_FAILED: '카카오톡 공유를 열지 못했어요',
  LINK_SUCCEEDED: (providerLabel: string) =>
    `${providerLabel} 계정을 연동했어요`,
  LINK_ALREADY_LINKED: '이미 연동된 계정이에요',
  LINK_FAILED: '계정 연동에 실패했어요',
  LINK_BLOCKED_IN_APP: '계정 연동은 외부 브라우저에서만 할 수 있어요',
  PUSH_PERMISSION_DENIED: '브라우저 알림이 차단되어 있어요',
  PUSH_SETTINGS_LOAD_FAILED: '알림 설정을 불러오지 못했어요',
  PUSH_SETTINGS_SAVE_FAILED: '알림 설정을 저장하지 못했어요',
  DRAFT_IMAGE_UPLOAD_FAILED: '이미지를 올리지 못했어요',
} as const;
