export const TOAST_MESSAGE = {
  STORY_COMPLETED: '스토리를 완성했어요',
  STORY_DELETED: '스토리를 삭제했어요',
  CHAT_DELETED: '채팅을 삭제했어요',
  STORY_DELETE_FAILED: '스토리 삭제에 실패했어요',
  CHAT_DELETE_FAILED: '채팅 삭제에 실패했어요',
  CHAT_START_FAILED: '채팅을 시작하지 못했어요',
  STORYLINE_LIKED: '좋아요를 남겼어요',
  STORYLINE_DISLIKED: '싫어요를 남겼어요',
  STORYLINE_EVALUATE_FAILED: '평가 저장에 실패했어요',
  RESPONSE_STREAM_FAILED: '응답 생성에 실패했어요',
  FEEDBACK_SUBMITTED: '소중한 피드백을 보내주셔서 감사해요',
  FEEDBACK_SUBMIT_FAILED: '피드백 전송에 실패했어요',
  LOGIN_FAILED: '로그인에 실패했어요',
  SESSION_EXPIRED: '세션이 만료되어 로그아웃되었어요',
  ATTENDANCE_CLAIMED: (amount: number) =>
    `출석 체크 보상으로 ${amount} 크레딧을 받았어요`,
  ATTENDANCE_ALREADY: '오늘은 이미 출석 체크했어요',
  ATTENDANCE_FAILED: '출석 체크에 실패했어요',
} as const;
