export const TOAST_MESSAGE = {
  STORY_COMPLETED: '스토리가 완성되었어요',
  STORY_DRAFT_SAVED: '스토리가 임시 저장되었어요',
  STORY_DELETED: '스토리가 삭제되었어요',
  CHAT_DELETED: '채팅이 삭제되었어요',
  STORY_DELETE_FAILED: '스토리 삭제에 실패했어요',
  CHAT_DELETE_FAILED: '채팅 삭제에 실패했어요',
  CHAT_START_FAILED: '채팅을 시작하지 못했어요',
  STORYLINE_LIKED: '좋아요를 남겼어요',
  STORYLINE_DISLIKED: '싫어요를 남겼어요',
  STORYLINE_EVALUATE_FAILED: '평가 저장에 실패했어요',
  RESPONSE_STREAM_FAILED: '응답 생성에 실패했어요',
  FEEDBACK_SUBMITTED: '소중한 피드백을 보내주셔서 감사해요',
  FEEDBACK_SUBMIT_FAILED: '피드백 전송에 실패했어요',
  LOGIN_FAILED: '로그인에 실패했어요',
  HANDOFF_CREATE_FAILED: '로그인 준비에 실패했어요. 잠시 후 다시 시도해주세요',
  LINK_COPIED: '링크를 복사했어요',
  LINK_COPY_FAILED: '링크 복사에 실패했어요',
  SESSION_EXPIRED: '세션이 만료되어 로그아웃되었어요',
  MIGRATION_SUCCEEDED: (storyCount: number, chatCount: number) =>
    `스토리 ${storyCount}개, 채팅 ${chatCount}개를 계정으로 옮겼어요`,
  MIGRATION_ALREADY_DONE:
    '이미 옮긴 적이 있어 이 기기의 스토리와 채팅은 옮기지 못했어요',
  ATTENDANCE_CLAIMED: (amount: number) =>
    `출석 체크 보상으로 ${amount} 크레딧을 받았어요`,
  ATTENDANCE_ALREADY: '오늘은 이미 출석 체크했어요',
  ATTENDANCE_FAILED: '출석 체크에 실패했어요',
  INVITE_CODE_COPIED: '초대 코드를 복사했어요',
  INVITE_CODE_COPY_FAILED: '초대 코드 복사에 실패했어요',
  INVITE_REDEEMED: '친구 초대 보상으로 500 크레딧을 받았어요',
  INVITE_ONBOARDING_SAVE_FAILED: '창을 닫지 못했어요',
  INVITE_SHARE_FAILED: '카카오톡 공유를 열지 못했어요',
} as const;
